const app = document.getElementById("app");

const defaultUsers = [
  {id:"demo", username:"ScratchFan", originalName:"scratch_user", avatar:"😺", bio:"Scratchでゲームを作っています！", videos:["Scratch作品紹介"], extensions:["便利なペン拡張"]},
  {id:"tw", username:"TurboCoder", originalName:"turbo_user", avatar:"🧩", bio:"TurboWarp拡張機能を制作しています。", videos:["制作過程"], extensions:["高速描画拡張"]},
  {id:"music", username:"MusicMaker", originalName:"music_user", avatar:"🎵", bio:"Scratchで音楽作品を作っています。", videos:["ゲームプレイ"], extensions:[]}
];

const defaultVideos = [
  {id:"v1", title:"Scratch作品紹介", userId:"demo", thumb:"🎮", description:"Scratchで作った作品を紹介します。"},
  {id:"v2", title:"制作過程", userId:"tw", thumb:"🛠️", description:"TurboWarpで作品を制作している様子です。"},
  {id:"v3", title:"ゲームプレイ", userId:"music", thumb:"▶️", description:"Scratch作品のプレイ動画です。"}
];

const state = {
  screen: "login", menu:false,
  language: localStorage.getItem("ls_language") || "ja",
  theme: localStorage.getItem("ls_theme") || "black",
  user: JSON.parse(localStorage.getItem("ls_user") || "null"),
  code:null, room:null, profileId:null, videoId:null,
  messages:[],
  participants:["demo","tw","music"]
};

const i18n = {
 ja:{login:"ログイン",name:"アカウント名",next:"次へ",code:"認証コード",verify:"認証する",roomSelect:"ルーム選択",publicRooms:"公開ルーム",createRoom:"ルームを作成",joinCode:"コードで参加",menu:"メニュー",search:"ルーム / Userを検索",rooms:"ルーム",videos:"動画",history:"履歴",friends:"友達",extensions:"TurboWarp拡張機能",settings:"アカウント設定",logout:"ログアウト",chat:"チャット",mic:"マイク",speaker:"相手の音声",record:"録音",profile:"アカウント",bio:"自己紹介",username:"Username",language:"言語",delete:"アカウント削除",save:"保存",back:"戻る",theme:"色味",videoSearch:"動画を検索",searchButton:"検索",participants:"参加中のユーザー",myAccount:"自分のアカウント",videosPosted:"投稿した動画",extensionsPosted:"公開したTurboWarp拡張機能",original:"Scratch User名",noResults:"見つかりませんでした",watch:"動画を見る",friendRequest:"友達申請",sendDM:"DMを送る"},
 en:{login:"Log in",name:"Account name",next:"Next",code:"Verification code",verify:"Verify",roomSelect:"Room selection",publicRooms:"Public rooms",createRoom:"Create room",joinCode:"Join by code",menu:"Menu",search:"Search rooms / users",rooms:"Rooms",videos:"Videos",history:"History",friends:"Friends",extensions:"TurboWarp extensions",settings:"Account settings",logout:"Log out",chat:"Chat",mic:"Microphone",speaker:"Other users' audio",record:"Record",profile:"Account",bio:"Bio",username:"Username",language:"Language",delete:"Delete account",save:"Save",back:"Back",theme:"Theme",videoSearch:"Search videos",searchButton:"Search",participants:"Users in this room",myAccount:"My account",videosPosted:"Posted videos",extensionsPosted:"Published TurboWarp extensions",original:"Scratch User name",noResults:"No results",watch:"Watch video",friendRequest:"Add friend",sendDM:"Send DM"}
};
function t(k){return (i18n[state.language]||i18n.ja)[k]||k}
function allUsers(){return [...defaultUsers, state.user&&{id:"me",...state.user}].filter(Boolean)}
function userById(id){return allUsers().find(u=>u.id===id)||defaultUsers.find(u=>u.id===id)}
function videoById(id){return defaultVideos.find(v=>v.id===id)}
function currentUser(){return state.user || {id:"me",username:"Guest",originalName:"",avatar:"🙂",bio:"",videos:[],extensions:[]}}
function render(){document.body.dataset.theme=state.theme; if(state.screen==="login")return renderLogin();if(state.screen==="verify")return renderVerify();if(state.screen==="rooms")return renderRooms();if(state.screen==="room")return renderRoom();if(state.screen==="profile")return renderProfile(state.profileId);if(state.screen==="video")return renderVideo(state.videoId);return renderPage(state.screen)}

function renderLogin(){app.innerHTML=`<main class="screen center"><section class="card"><h1 class="title">LiveScratch-remake</h1><p class="sub">${t("login")}</p><input id="name" class="field" placeholder="${t("name")}"><button class="btn" id="next">${t("next")}</button><p class="hint">Phase 1試作版：認証コードはデモ生成です。</p></section></main>`;document.getElementById("next").onclick=()=>{const name=document.getElementById("name").value.trim();if(!name)return toast("アカウント名を入力してください");state.code=String(Math.floor(100000+Math.random()*900000));state.user={id:"me",originalName:name,username:name,avatar:"🙂",bio:"",videos:[],extensions:[]};state.screen="verify";render();toast("デモ認証コード: "+state.code)}}
function renderVerify(){app.innerHTML=`<main class="screen center"><section class="card"><h1 class="title">${t("code")}</h1><p class="sub">10分間だけ有効なコード（試作版）</p><input id="code" class="field" inputmode="numeric" placeholder="123456"><button class="btn" id="verify">${t("verify")}</button><p id="err" class="error"></p></section></main>`;document.getElementById("verify").onclick=()=>{if(document.getElementById("code").value!==state.code){document.getElementById("err").textContent="コードが違います。";return}localStorage.setItem("ls_user",JSON.stringify(state.user));state.screen="rooms";render()}}

function menu(){return `<button class="menu-btn" id="menuBtn" aria-label="menu">☰</button><div class="menu-overlay ${state.menu?"show":""}" id="menuOverlay"></div><aside class="sidebar ${state.menu?"open":""}"><div class="side-title">${t("menu")}</div>${[["search","🔎"],["rooms","🏠"],["videos","🎬"],["history","📜"],["friends","👥"],["extensions","🧩"],["settings","⚙️"],["logout","🚪"]].map(([x,icon])=>`<button class="menu-item" data-page="${x}">${icon} ${t(x)}</button>`).join("")}</aside>`}
function bindMenu(){const btn=document.getElementById("menuBtn");if(btn)btn.onclick=()=>{state.menu=!state.menu;render()};const overlay=document.getElementById("menuOverlay");if(overlay)overlay.onclick=()=>{state.menu=false;render()};document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{const p=b.dataset.page;if(p==="logout"){localStorage.removeItem("ls_user");state.user=null;state.screen="login";state.menu=false;render();return}state.screen=p;state.menu=false;render()})}

function renderRooms(){const rooms=["Scratch雑談ルーム","作品制作ルーム","TurboWarp開発ルーム"];app.innerHTML=`${menu()}<div class="topbar"><span class="room-name">${t("roomSelect")}</span></div><main><div class="room-actions"><button class="btn" id="create">${t("createRoom")}</button><button class="btn secondary" id="join">${t("joinCode")}</button></div><h2 class="section-title">${t("publicRooms")}</h2><div class="room-grid">${rooms.map((r,i)=>`<article class="room-card"><h3>${r}</h3><p>公開ルーム · ${i+2}人参加中</p><button class="btn" data-room="${escapeAttr(r)}">参加</button></article>`).join("")}</div></main>`;bindMenu();document.getElementById("create").onclick=()=>{const n=prompt("ルーム名");if(n)enterRoom(n)};document.getElementById("join").onclick=()=>{const c=prompt("ルームコード");if(c)enterRoom("コード "+c)};document.querySelectorAll("[data-room]").forEach(b=>b.onclick=()=>enterRoom(b.dataset.room))}
function enterRoom(name){state.room=name;state.screen="room";state.menu=false;state.messages=[{user:"System",text:`${name} に参加しました。`}];render()}

function participantCard(id){const u=userById(id);if(!u)return "";return `<button class="participant" data-user="${escapeAttr(id)}"><span class="mini-avatar">${escapeHtml(u.avatar)}</span><span><b>${escapeHtml(u.username)}</b><small>${escapeHtml(u.originalName)}</small></span></button>`}
function renderRoom(){const ids=["demo","tw","music"];if(state.user)ids.push("me");app.innerHTML=`${menu()}<div class="topbar"><span class="room-name">🏠 ${escapeHtml(state.room||"Room")}</span></div><main class="room-layout"><section class="chat"><div class="chat-head">${t("chat")}</div><div class="messages" id="messages">${state.messages.map(m=>`<div class="message"><b>${escapeHtml(m.user)}</b><span>${escapeHtml(m.text)}</span></div>`).join("")}</div><div class="voice"><button class="btn secondary" id="mic">🎙️ ${t("mic")} ON</button><button class="btn secondary" id="speaker">🔊 ${t("speaker")} ON</button><button class="btn secondary" id="record">⏺ ${t("record")}</button></div><div class="chat-controls"><input id="msg" class="chat-input" placeholder="メッセージ..."></div></section><section class="tw"><div class="tw-placeholder"><strong>TurboWarp</strong><span>ここにTurboWarpを接続します（Phase 2以降）</span></div></section><aside class="participants"><h3>👥 ${t("participants")}</h3>${ids.map(participantCard).join("")}</aside></main>`;bindMenu();document.querySelectorAll("[data-user]").forEach(x=>x.onclick=()=>{state.profileId=x.dataset.user;state.screen="profile";state.menu=false;render()});const msg=document.getElementById("msg");msg.addEventListener("keydown",e=>{if(e.key==="Enter"&&msg.value.trim()){state.messages.push({user:currentUser().username,text:msg.value.trim()});msg.value="";render()}});let mic=true,speaker=true,recording=false;document.getElementById("mic").onclick=()=>{mic=!mic;document.getElementById("mic").textContent=`🎙️ ${t("mic")} ${mic?"ON":"OFF"}`};document.getElementById("speaker").onclick=()=>{speaker=!speaker;document.getElementById("speaker").textContent=`🔊 ${t("speaker")} ${speaker?"ON":"OFF"}`};document.getElementById("record").onclick=()=>{recording=!recording;document.getElementById("record").textContent=recording?"⏹ 録音停止":"⏺ 録音"}}

function renderPage(page){const title=t(page);let body="";if(page==="search")body=searchPage();if(page==="videos")body=videosPage();if(page==="history")body=`<div class="panel"><h2>${title}</h2><h3>入ったルーム</h3><p>まだ履歴はありません。</p><h3>見た動画</h3><p>まだ履歴はありません。</p></div>`;if(page==="friends")body=`<div class="panel"><h2>${title}</h2><p>友達がここに表示され、承認済みの友達へDMできます。</p></div>`;if(page==="extensions")body=extensionsPage();if(page==="settings")body=settingsPage();if(page==="rooms")return renderRooms();app.innerHTML=`${menu()}<main class="page"><h1>${title}</h1>${body}</main>`;bindMenu();if(page==="settings")bindSettings();if(page==="search")bindSearch();if(page==="videos")bindVideoSearch()}

function searchPage(){return `<div class="panel"><h2>🔎 ${t("search")}</h2><input id="globalSearch" class="field" placeholder="User名 / Scratch User名 / ルーム名"><button class="btn" id="globalSearchBtn">${t("searchButton")}</button><div id="searchResults" class="search-results"></div></div>`}
function bindSearch(){document.getElementById("globalSearchBtn").onclick=runGlobalSearch;document.getElementById("globalSearch").addEventListener("keydown",e=>{if(e.key==="Enter")runGlobalSearch()})}
function runGlobalSearch(){const q=document.getElementById("globalSearch").value.toLowerCase();const users=allUsers().filter(u=>(u.username+u.originalName).toLowerCase().includes(q));const rooms=["Scratch雑談ルーム","作品制作ルーム","TurboWarp開発ルーム"].filter(r=>r.toLowerCase().includes(q));document.getElementById("searchResults").innerHTML=(users.length?`<h3>User</h3>${users.map(u=>participantCard(u.id)).join("")}:`:'')+(rooms.length?`<h3>ルーム</h3>${rooms.map(r=>`<button class="result-room" data-room="${escapeAttr(r)}">🏠 ${escapeHtml(r)}</button>`).join("")}`:'')||`<p class="sub">${t("noResults")}</p>`;document.querySelectorAll("#searchResults [data-user]").forEach(x=>x.onclick=()=>{state.profileId=x.dataset.user;state.screen="profile";render()});document.querySelectorAll(".result-room").forEach(x=>x.onclick=()=>enterRoom(x.dataset.room))}

function videosPage(){return `<div class="panel"><div class="search-line"><input id="videoSearch" class="field" value="" placeholder="${t("videoSearch")}（動画名 / User名）"><button class="btn" id="videoSearchBtn">${t("searchButton")}</button></div><p class="sub">Scratchの画面録画を投稿・視聴する場所です。</p><button class="btn">動画を投稿</button></div><div id="videoGrid" class="video-grid">${defaultVideos.map(videoCard).join("")}</div>`}
function videoCard(v){const u=userById(v.userId);return `<article class="video-card"><button class="video-thumb" data-video="${escapeAttr(v.id)}">${escapeHtml(v.thumb)}<span>▶</span></button><div class="video-info"><button class="link-title" data-video="${escapeAttr(v.id)}">${escapeHtml(v.title)}</button><button class="user-link" data-user="${escapeAttr(v.userId)}">${escapeHtml(u?.avatar||"🙂")} ${escapeHtml(u?.username||"User")}</button></div></article>`}
function bindVideoSearch(){document.getElementById("videoSearchBtn").onclick=filterVideos;document.getElementById("videoSearch").addEventListener("keydown",e=>{if(e.key==="Enter")filterVideos()});bindVideoLinks()}
function bindVideoLinks(){document.querySelectorAll("[data-video]").forEach(x=>x.onclick=()=>{state.videoId=x.dataset.video;state.screen="video";render()});document.querySelectorAll("[data-user]").forEach(x=>x.onclick=()=>{state.profileId=x.dataset.user;state.screen="profile";render()})}
function filterVideos(){const q=document.getElementById("videoSearch").value.toLowerCase();const vs=defaultVideos.filter(v=>{const u=userById(v.userId);return (v.title+(u?.username||"")+(u?.originalName||"")).toLowerCase().includes(q)});document.getElementById("videoGrid").innerHTML=vs.length?vs.map(videoCard).join(""):`<p class="sub">${t("noResults")}</p>`;bindVideoLinks()}
function renderVideo(id){const v=videoById(id);if(!v){state.screen="videos";return render()}const u=userById(v.userId);app.innerHTML=`${menu()}<main class="page"><button class="btn secondary back-btn" id="back">← ${t("back")}</button><section class="video-detail"><div class="big-video">${escapeHtml(v.thumb)}<span>▶</span></div><h1>${escapeHtml(v.title)}</h1><button class="account-row" data-user="${escapeAttr(v.userId)}"><span class="mini-avatar">${escapeHtml(u.avatar)}</span><b>${escapeHtml(u.username)}</b></button><p>${escapeHtml(v.description)}</p></section></main>`;bindMenu();document.getElementById("back").onclick=()=>{state.screen="videos";render()};document.querySelector("[data-user]").onclick=()=>{state.profileId=v.userId;state.screen="profile";render()}}

function profileVideos(u){return (u.videos||[]).map(name=>defaultVideos.find(v=>v.title===name)).filter(Boolean)}
function renderProfile(id){const u=userById(id)||currentUser();const mine=id==="me";const vs=profileVideos(u);const ex=u.extensions||[];app.innerHTML=`${menu()}<main class="page profile-page"><button class="btn secondary back-btn" id="profileBack">← ${t("back")}</button><section class="profile-hero"><div class="avatar large">${escapeHtml(u.avatar)}</div><div><h1>${escapeHtml(u.username)}</h1><div class="scratch-name">${t("original")}: ${escapeHtml(u.originalName)}</div></div></section><section class="panel"><h2>${t("bio")}</h2><p>${escapeHtml(u.bio||"まだ自己紹介はありません。")}</p>${!mine?`<div class="row"><button class="btn" id="friendRequest">👥 ${t("friendRequest")}</button><button class="btn secondary">💬 ${t("sendDM")}</button></div>`:""}</section><section class="panel"><h2>🎬 ${t("videosPosted")}</h2><div class="video-grid">${vs.length?vs.map(videoCard).join(""):`<p class="sub">まだ投稿された動画はありません。</p>`}</div></section><section class="panel"><h2>🧩 ${t("extensionsPosted")}</h2>${ex.length?ex.map(x=>`<div class="extension-card"><b>${escapeHtml(x)}</b><p>TurboWarp用JavaScript拡張機能</p></div>`).join(""):`<p class="sub">まだ公開された拡張機能はありません。</p>`}</section></main>`;bindMenu();document.getElementById("profileBack").onclick=()=>{state.screen="rooms";render()};bindVideoLinks();const fr=document.getElementById("friendRequest");if(fr)fr.onclick=()=>toast("友達申請を送りました（試作版）")}

function extensionsPage(){return `<div class="panel"><h2>${t("extensions")}</h2><p>スクラッチャーが作ったTurboWarp拡張機能のJavaScriptを公開する場所です。</p><button class="btn">拡張機能を公開</button></div><div class="extension-card"><b>高速描画拡張</b><p>作者: TurboCoder</p><button class="btn secondary" data-user="tw">作者のアカウントを見る</button></div>`}

function settingsPage(){const u=currentUser();return `<div class="panel"><div class="profile"><div class="avatar">${escapeHtml(u.avatar)}</div><div><h2>${escapeHtml(u.username)}</h2><small>${escapeHtml(u.originalName)}</small></div></div><button class="btn secondary" id="openMyProfile">${t("myAccount")}</button></div><div class="panel"><div class="setting-row"><div><b>${t("username")}</b><small>LiveScratch-remake上の表示名</small></div><input id="username" class="field small-field" value="${escapeAttr(u.username)}"></div><div class="setting-row"><div><b>アイコン</b></div><input id="avatar" class="field tiny-field" value="${escapeAttr(u.avatar)}"></div><div class="setting-row"><div><b>${t("bio")}</b></div><textarea id="bio" class="field small-field">${escapeHtml(u.bio)}</textarea></div><div class="setting-row"><div><b>${t("language")}</b></div><select id="language" class="field select-field"><option value="ja" ${state.language==="ja"?"selected":""}>日本語</option><option value="en" ${state.language==="en"?"selected":""}>English</option></select></div><div class="setting-row"><div><b>${t("theme")}</b><small>画面全体の色味を変更</small></div><select id="theme" class="field select-field"><option value="black">⚫ 黒</option><option value="red">🔴 TurboWarpの赤</option><option value="blue">🔵 Scratchの青</option><option value="white">⚪ 白</option><option value="rainbow">🌈 レインボー</option></select></div><button class="btn" id="save">${t("save")}</button></div><div class="panel"><button class="btn danger" id="delete">${t("delete")}</button></div>`}
function bindSettings(){document.getElementById("theme").value=state.theme;document.getElementById("openMyProfile").onclick=()=>{state.profileId="me";state.screen="profile";render()};document.getElementById("save").onclick=()=>{state.user.username=document.getElementById("username").value.trim()||state.user.originalName;state.user.avatar=document.getElementById("avatar").value||"🙂";state.user.bio=document.getElementById("bio").value;state.language=document.getElementById("language").value;state.theme=document.getElementById("theme").value;localStorage.setItem("ls_user",JSON.stringify(state.user));localStorage.setItem("ls_language",state.language);localStorage.setItem("ls_theme",state.theme);render();toast("設定を保存しました")};document.getElementById("delete").onclick=()=>{if(confirm("試作版：ローカルのアカウント情報を削除します。よろしいですか？")){localStorage.clear();state.user=null;state.screen="login";render()}}}
function toast(s){const x=document.createElement("div");x.className="toast";x.textContent=s;document.body.appendChild(x);setTimeout(()=>x.remove(),3000)}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function escapeAttr(s=""){return escapeHtml(s)}
render();
